import { Router, type IRouter } from "express";
import healthRouter from "./health";
import matchesRouter from "./matches";
import teamsRouter from "./teams";
import streamsRouter from "./streams";
import highlightsRouter from "./highlights";
import statsRouter from "./stats";
import tournamentsRouter from "./tournaments";
import eventsRouter from "./events";
import lineupRouter from "./lineup";
import adminAuthRouter from "./admin-auth";
import adminStaffRouter from "./admin-staff";
import squadRouter from "./squad";
import bannersRouter from "./banners";
import spotlightsRouter from "./spotlights";
import seedRouter from "./seed";
import pushRouter from "./push";
import trophiesRouter from "./trophies";

const router: IRouter = Router();

router.use(adminAuthRouter);
router.use(adminStaffRouter);
router.use(squadRouter);
router.use(healthRouter);
router.use(matchesRouter);
router.use(teamsRouter);
router.use(streamsRouter);
router.use(highlightsRouter);
router.use(statsRouter);
router.use(tournamentsRouter);
router.use(eventsRouter);
router.use(lineupRouter);
router.use(bannersRouter);
router.use(spotlightsRouter);
router.use(seedRouter);
router.use(pushRouter);
router.use(trophiesRouter);

export default router;
